apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
  - name: registry-tcp
    port: 5000
    nodePort: 32500
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registrydata
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - resources:
        name: registry
        image: registry:2
        ports:
        - name: registry-port
          containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registryvolume
        - mountPath: /certs
          name: registryvolume
        - mountPath: /auth
          name: registryvolume
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/fullchain1.pem
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/privkey1.pem
      volumes:
      - name: registryvolume
        persistentVolumeClaim:
          claimName: registrydata
